name: mam_projekt_v1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_social_button: ^1.1.4+1
  font_awesome_flutter: ^10.7.0
  glass_container: ^0.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    
    - assets/icons/ContentSwitcher/
    - assets/images/
    - assets/icons/
    - assets/icons/Logos/logo-transparent.png
    - assets/icons/Logos/google_logo.png
    - assets/icons/Calendar/
    - assets/images/News/
    - assets/images/TrashCanColor/



fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-Italic.ttf
          style: italic