name: mam_projekt_v1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_social_button: ^1.1.4+1
  font_awesome_flutter: ^10.7.0
  glass_container: ^0.0.4
  shared_preferences: ^2.3.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 


flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "assets/icons/Logos/logo.png" 
  adaptive_icon_foreground: "assets/icons/Logos/logo.png"
  image_path: "assets/icons/Logos/logo.png"

flutter:
  uses-material-design: true

  assets:
    
    - assets/icons/ContentSwitcher/
    - assets/images/
    - assets/icons/
    - assets/icons/Logos/logo-transparent.png
    - assets/icons/Logos/google_logo.png
    - assets/icons/Calendar/
    - assets/images/News/
    - assets/images/TrashCanColor/
    - assets/images/TrashCanColor/Muellabfuhr.jpeg
   



fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-Italic.ttf
          style: italic